from __future__ import annotations

from .models import (
    ActionAvailability,
    ActionAvailabilityScope,
    ActionCategory,
    ActionDefinition,
    ActionSyncMode,
    CapabilityDefinition,
    MissionStatus,
    RunStatus,
    SafetyLevel,
    SimulationSessionStatus,
)


def _availability(scope: ActionAvailabilityScope, *allowed_statuses: str) -> tuple[ActionAvailability, ...]:
    return (ActionAvailability(scope=scope, allowed_statuses=allowed_statuses),)


_NO_GATING: tuple[ActionAvailability, ...] = ()
_SESSION_STARTABLE = _availability(
    ActionAvailabilityScope.SIMULATION_SESSION,
    SimulationSessionStatus.IDLE.value,
    SimulationSessionStatus.STOPPED.value,
    SimulationSessionStatus.FAILED.value,
)
_SESSION_ACTIVE = _availability(
    ActionAvailabilityScope.SIMULATION_SESSION,
    SimulationSessionStatus.ACTIVE.value,
    SimulationSessionStatus.DEGRADED.value,
)
_SESSION_STOPPABLE = _availability(
    ActionAvailabilityScope.SIMULATION_SESSION,
    SimulationSessionStatus.STARTING.value,
    SimulationSessionStatus.ACTIVE.value,
    SimulationSessionStatus.DEGRADED.value,
    SimulationSessionStatus.FAILED.value,
)
_SESSION_ANY = _availability(
    ActionAvailabilityScope.SIMULATION_SESSION,
    SimulationSessionStatus.IDLE.value,
    SimulationSessionStatus.STARTING.value,
    SimulationSessionStatus.ACTIVE.value,
    SimulationSessionStatus.DEGRADED.value,
    SimulationSessionStatus.STOPPING.value,
    SimulationSessionStatus.STOPPED.value,
    SimulationSessionStatus.FAILED.value,
)
_RUN_ACTIVE = _availability(
    ActionAvailabilityScope.RUN,
    RunStatus.STARTING.value,
    RunStatus.RUNNING.value,
)
_MISSION_ACTIVE = _availability(
    ActionAvailabilityScope.MISSION,
    MissionStatus.ARMING.value,
    MissionStatus.TAKEOFF.value,
    MissionStatus.HOVER.value,
    MissionStatus.PATROL.value,
    MissionStatus.RETURNING.value,
    MissionStatus.LANDING.value,
    MissionStatus.ABORTING.value,
)
_MISSION_RESETTABLE = _availability(
    ActionAvailabilityScope.MISSION,
    MissionStatus.COMPLETED.value,
    MissionStatus.ABORTED.value,
    MissionStatus.FAILED.value,
)
_MISSION_ANY = _availability(
    ActionAvailabilityScope.MISSION,
    MissionStatus.IDLE.value,
    MissionStatus.ARMING.value,
    MissionStatus.TAKEOFF.value,
    MissionStatus.HOVER.value,
    MissionStatus.PATROL.value,
    MissionStatus.RETURNING.value,
    MissionStatus.LANDING.value,
    MissionStatus.ABORTING.value,
    MissionStatus.COMPLETED.value,
    MissionStatus.ABORTED.value,
    MissionStatus.FAILED.value,
)


INITIAL_ACTION_CATALOG: tuple[ActionDefinition, ...] = (
    ActionDefinition(
        action_name="simulation.start",
        category=ActionCategory.SIMULATION,
        description="Start the simulation runtime session through the control plane.",
        input_schema="SimulationStartRequest",
        result_schema="ActionResult",
        target="simulation",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_SESSION_STARTABLE,
        owner_runtime="shell_adapter",
    ),
    ActionDefinition(
        action_name="simulation.stop",
        category=ActionCategory.SIMULATION,
        description="Stop the active simulation runtime session.",
        input_schema="SimulationStopRequest",
        result_schema="ActionResult",
        target="simulation",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_SESSION_STOPPABLE,
        owner_runtime="shell_adapter",
    ),
    ActionDefinition(
        action_name="simulation.restart",
        category=ActionCategory.SIMULATION,
        description="Restart the simulation runtime session through the control plane.",
        input_schema="SimulationRestartRequest",
        result_schema="ActionResult",
        target="simulation",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_SESSION_ANY,
        owner_runtime="shell_adapter",
    ),
    ActionDefinition(
        action_name="simulation.status.get",
        category=ActionCategory.SIMULATION,
        description="Read the current simulation session status.",
        input_schema="EmptyObject",
        result_schema="SimulationSession",
        target="simulation",
        sync_mode=ActionSyncMode.SYNC,
        availability=_SESSION_ANY,
        owner_runtime="control_plane",
        read_only=True,
    ),
    ActionDefinition(
        action_name="capabilities.list",
        category=ActionCategory.DISCOVERY,
        description="List capabilities exposed by the control plane for the current runtime.",
        input_schema="EmptyObject",
        result_schema="CapabilityList",
        target="capability_registry",
        sync_mode=ActionSyncMode.SYNC,
        availability=_NO_GATING,
        owner_runtime="control_plane",
        read_only=True,
    ),
    ActionDefinition(
        action_name="scenario.list",
        category=ActionCategory.SCENARIO,
        description="List the scenarios exposed by the control plane.",
        input_schema="EmptyObject",
        result_schema="ScenarioList",
        target="scenario_registry",
        sync_mode=ActionSyncMode.SYNC,
        availability=_SESSION_ANY,
        owner_runtime="control_plane",
        read_only=True,
    ),
    ActionDefinition(
        action_name="scenario.run",
        category=ActionCategory.SCENARIO,
        description="Run a scenario without leaking its executor type to the caller.",
        input_schema="ScenarioRunRequest",
        result_schema="ActionResult",
        target="scenario",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_SESSION_ACTIVE,
        owner_runtime="scenario_runtime",
    ),
    ActionDefinition(
        action_name="scenario.cancel",
        category=ActionCategory.SCENARIO,
        description="Request cancellation of an active scenario run.",
        input_schema="ScenarioCancelRequest",
        result_schema="ActionResult",
        target="scenario",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_RUN_ACTIVE,
        owner_runtime="scenario_runtime",
    ),
    ActionDefinition(
        action_name="scenario.status.get",
        category=ActionCategory.SCENARIO,
        description="Read the current run status for a scenario.",
        input_schema="ScenarioStatusQuery",
        result_schema="ScenarioStatus",
        target="scenario",
        sync_mode=ActionSyncMode.SYNC,
        availability=_NO_GATING,
        owner_runtime="control_plane",
        read_only=True,
    ),
    ActionDefinition(
        action_name="mission.start",
        category=ActionCategory.MISSION,
        description="Request mission execution through the ROS 2 mission runtime.",
        input_schema="MissionStartRequest",
        result_schema="ActionResult",
        target="mission",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_SESSION_ACTIVE + _availability(ActionAvailabilityScope.MISSION, MissionStatus.IDLE.value),
        owner_runtime="ros2_adapter",
    ),
    ActionDefinition(
        action_name="mission.abort",
        category=ActionCategory.MISSION,
        description="Abort the active mission.",
        input_schema="MissionAbortRequest",
        result_schema="ActionResult",
        target="mission",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_MISSION_ACTIVE,
        owner_runtime="ros2_adapter",
    ),
    ActionDefinition(
        action_name="mission.reset",
        category=ActionCategory.MISSION,
        description="Reset mission state after a terminal phase.",
        input_schema="MissionResetRequest",
        result_schema="ActionResult",
        target="mission",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_MISSION_RESETTABLE,
        owner_runtime="ros2_adapter",
    ),
    ActionDefinition(
        action_name="mission.status.get",
        category=ActionCategory.MISSION,
        description="Read the consolidated mission status.",
        input_schema="EmptyObject",
        result_schema="MissionDefinition",
        target="mission",
        sync_mode=ActionSyncMode.SYNC,
        availability=_MISSION_ANY,
        owner_runtime="read_model_adapter",
        read_only=True,
    ),
    ActionDefinition(
        action_name="vehicle.arm",
        category=ActionCategory.VEHICLE,
        description="Arm the active vehicle.",
        input_schema="EmptyObject",
        result_schema="ActionResult",
        target="vehicle",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_SESSION_ACTIVE,
        owner_runtime="ros2_adapter",
    ),
    ActionDefinition(
        action_name="vehicle.disarm",
        category=ActionCategory.VEHICLE,
        description="Disarm the active vehicle.",
        input_schema="EmptyObject",
        result_schema="ActionResult",
        target="vehicle",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_SESSION_ACTIVE,
        owner_runtime="ros2_adapter",
    ),
    ActionDefinition(
        action_name="vehicle.takeoff",
        category=ActionCategory.VEHICLE,
        description="Trigger a direct vehicle takeoff action.",
        input_schema="VehicleTakeoffRequest",
        result_schema="ActionResult",
        target="vehicle",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_SESSION_ACTIVE,
        owner_runtime="ros2_adapter",
    ),
    ActionDefinition(
        action_name="vehicle.land",
        category=ActionCategory.VEHICLE,
        description="Request a landing action.",
        input_schema="EmptyObject",
        result_schema="ActionResult",
        target="vehicle",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_SESSION_ACTIVE,
        owner_runtime="ros2_adapter",
    ),
    ActionDefinition(
        action_name="vehicle.return_to_home",
        category=ActionCategory.VEHICLE,
        description="Request return-to-home for the current vehicle.",
        input_schema="EmptyObject",
        result_schema="ActionResult",
        target="vehicle",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_SESSION_ACTIVE,
        owner_runtime="ros2_adapter",
    ),
    ActionDefinition(
        action_name="vehicle.goto",
        category=ActionCategory.VEHICLE,
        description="Request a goto operation using product-level coordinates.",
        input_schema="VehicleGotoRequest",
        result_schema="ActionResult",
        target="vehicle",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_SESSION_ACTIVE,
        owner_runtime="ros2_adapter",
    ),
    ActionDefinition(
        action_name="safety.inject_fault",
        category=ActionCategory.SAFETY,
        description="Inject a safety fault through the protected safety runtime.",
        input_schema="SafetyFaultInjectionRequest",
        result_schema="ActionResult",
        target="safety",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_SESSION_ACTIVE,
        owner_runtime="ros2_adapter",
    ),
    ActionDefinition(
        action_name="safety.clear_fault",
        category=ActionCategory.SAFETY,
        description="Clear a previously injected safety fault.",
        input_schema="SafetyFaultClearRequest",
        result_schema="ActionResult",
        target="safety",
        sync_mode=ActionSyncMode.ASYNC,
        availability=_SESSION_ACTIVE,
        owner_runtime="ros2_adapter",
    ),
    ActionDefinition(
        action_name="safety.status.get",
        category=ActionCategory.SAFETY,
        description="Read the current safety status.",
        input_schema="EmptyObject",
        result_schema="SafetyStatus",
        target="safety",
        sync_mode=ActionSyncMode.SYNC,
        availability=_SESSION_ANY,
        owner_runtime="read_model_adapter",
        read_only=True,
    ),
    ActionDefinition(
        action_name="perception.status.get",
        category=ActionCategory.PERCEPTION,
        description="Read the perception pipeline operational status.",
        input_schema="EmptyObject",
        result_schema="PerceptionStatus",
        target="perception",
        sync_mode=ActionSyncMode.SYNC,
        availability=_SESSION_ACTIVE,
        owner_runtime="read_model_adapter",
        read_only=True,
    ),
    ActionDefinition(
        action_name="perception.stream.status.get",
        category=ActionCategory.PERCEPTION,
        description="Read the camera or perception stream availability state.",
        input_schema="EmptyObject",
        result_schema="PerceptionStreamStatus",
        target="perception_stream",
        sync_mode=ActionSyncMode.SYNC,
        availability=_SESSION_ACTIVE,
        owner_runtime="read_model_adapter",
        read_only=True,
    ),
    ActionDefinition(
        action_name="telemetry.snapshot.get",
        category=ActionCategory.TELEMETRY,
        description="Read the consolidated telemetry snapshot.",
        input_schema="EmptyObject",
        result_schema="TelemetrySnapshot",
        target="read_model",
        sync_mode=ActionSyncMode.SYNC,
        availability=_SESSION_ANY,
        owner_runtime="read_model_adapter",
        read_only=True,
    ),
    ActionDefinition(
        action_name="telemetry.metrics.get",
        category=ActionCategory.TELEMETRY,
        description="Read telemetry metrics for the active or requested run.",
        input_schema="TelemetryMetricsQuery",
        result_schema="TelemetryMetrics",
        target="read_model",
        sync_mode=ActionSyncMode.SYNC,
        availability=_SESSION_ANY,
        owner_runtime="read_model_adapter",
        read_only=True,
    ),
    ActionDefinition(
        action_name="telemetry.events.get",
        category=ActionCategory.TELEMETRY,
        description="Read persisted telemetry events.",
        input_schema="TelemetryEventsQuery",
        result_schema="TelemetryEvents",
        target="read_model",
        sync_mode=ActionSyncMode.SYNC,
        availability=_SESSION_ANY,
        owner_runtime="read_model_adapter",
        read_only=True,
    ),
    ActionDefinition(
        action_name="telemetry.runs.list",
        category=ActionCategory.TELEMETRY,
        description="List control-plane visible runs.",
        input_schema="EmptyObject",
        result_schema="RunList",
        target="read_model",
        sync_mode=ActionSyncMode.SYNC,
        availability=_SESSION_ANY,
        owner_runtime="read_model_adapter",
        read_only=True,
    ),
    ActionDefinition(
        action_name="telemetry.replay.get",
        category=ActionCategory.TELEMETRY,
        description="Read replay data for a given run.",
        input_schema="TelemetryReplayQuery",
        result_schema="TelemetryReplay",
        target="read_model",
        sync_mode=ActionSyncMode.SYNC,
        availability=_SESSION_ANY,
        owner_runtime="read_model_adapter",
        read_only=True,
    ),
)


INITIAL_CAPABILITY_CATALOG: tuple[CapabilityDefinition, ...] = (
    CapabilityDefinition(
        capability_name="simulation.lifecycle",
        version="1.0.0",
        description="Manage the simulation session lifecycle through the control plane.",
        action_names=("simulation.start", "simulation.stop", "simulation.restart", "simulation.status.get"),
        required_runtime_components=("simulation", "px4", "gazebo", "micro_xrce_dds_agent"),
        constraints={"visual_supported": True, "headless_supported": True},
        owner_runtime="shell_adapter",
        safety_level=SafetyLevel.GUARDED,
    ),
    CapabilityDefinition(
        capability_name="scenario.takeoff_land.run",
        version="1.0.0",
        description="Run the takeoff_land scenario against the active runtime.",
        action_names=("scenario.run", "scenario.cancel", "scenario.status.get"),
        required_runtime_components=("simulation", "px4", "gazebo", "mavsdk"),
        constraints={"scenario_name": "takeoff_land", "visual_supported": True, "headless_supported": True},
        owner_runtime="mavsdk_adapter",
        safety_level=SafetyLevel.GUARDED,
    ),
    CapabilityDefinition(
        capability_name="scenario.patrol_basic.run",
        version="1.0.0",
        description="Run the patrol_basic mission-backed scenario through the control plane.",
        action_names=("scenario.run", "scenario.cancel", "scenario.status.get"),
        required_runtime_components=("simulation", "ros2", "mission_runtime", "px4"),
        constraints={"scenario_name": "patrol_basic", "visual_supported": True, "headless_supported": True},
        owner_runtime="mission_runtime",
        safety_level=SafetyLevel.GUARDED,
    ),
    CapabilityDefinition(
        capability_name="mission.control",
        version="1.0.0",
        description="Operate mission lifecycle actions without direct topic publishing.",
        action_names=("mission.start", "mission.abort", "mission.reset", "mission.status.get"),
        required_runtime_components=("ros2", "mission_runtime"),
        constraints={"requires_active_session": True},
        owner_runtime="mission_runtime",
        safety_level=SafetyLevel.GUARDED,
    ),
    CapabilityDefinition(
        capability_name="vehicle.basic_control",
        version="1.0.0",
        description="Operate core vehicle commands through the unified control surface.",
        action_names=(
            "vehicle.arm",
            "vehicle.disarm",
            "vehicle.takeoff",
            "vehicle.land",
            "vehicle.return_to_home",
            "vehicle.goto",
        ),
        required_runtime_components=("ros2", "px4"),
        constraints={"requires_connected_vehicle": True},
        owner_runtime="vehicle_runtime",
        safety_level=SafetyLevel.CRITICAL,
    ),
    CapabilityDefinition(
        capability_name="safety.fault_injection",
        version="1.0.0",
        description="Inject or clear faults through the safety runtime without bypassing its policy logic.",
        action_names=("safety.inject_fault", "safety.clear_fault", "safety.status.get"),
        required_runtime_components=("ros2", "safety_runtime"),
        constraints={"operator_confirmation_required": True},
        owner_runtime="safety_runtime",
        safety_level=SafetyLevel.CRITICAL,
    ),
    CapabilityDefinition(
        capability_name="telemetry.read_model",
        version="1.0.0",
        description="Read snapshot, metrics, events and run lists from the read model.",
        action_names=("telemetry.snapshot.get", "telemetry.metrics.get", "telemetry.events.get", "telemetry.runs.list"),
        required_runtime_components=("telemetry_api",),
        constraints={"read_only": True},
        owner_runtime="read_model",
        safety_level=SafetyLevel.NONE,
    ),
    CapabilityDefinition(
        capability_name="replay.read",
        version="1.0.0",
        description="Access persisted replay artifacts by run id.",
        action_names=("telemetry.replay.get",),
        required_runtime_components=("telemetry_api",),
        constraints={"read_only": True, "requires_run_id": True},
        owner_runtime="read_model",
        safety_level=SafetyLevel.NONE,
    ),
    CapabilityDefinition(
        capability_name="perception.observe",
        version="1.0.0",
        description="Observe perception heartbeat, detections and stream status.",
        action_names=("perception.status.get", "perception.stream.status.get", "telemetry.snapshot.get"),
        required_runtime_components=("ros2", "perception_runtime", "telemetry_api"),
        constraints={"stream_may_depend_on_environment": True},
        owner_runtime="perception_runtime",
        required_payloads=("camera",),
        safety_level=SafetyLevel.ADVISORY,
    ),
)
