import type {
  ActionAvailability,
  ActionAvailabilityScope,
  ActionDefinition,
  CapabilityDefinition,
} from "./contracts";

const availability = (scope: ActionAvailabilityScope, ...allowed_statuses: string[]): ActionAvailability[] => [
  { scope, allowed_statuses },
];

const sessionStartable = availability("simulation_session", "idle", "stopped", "failed");
const sessionActive = availability("simulation_session", "active", "degraded");
const sessionStoppable = availability("simulation_session", "starting", "active", "degraded", "failed");
const sessionAny = availability("simulation_session", "idle", "starting", "active", "degraded", "stopping", "stopped", "failed");
const runActive = availability("run", "starting", "running");
const missionActive = availability("mission", "arming", "takeoff", "hover", "patrol", "returning", "landing");
const missionResettable = availability("mission", "completed", "aborted", "failed");
const missionAny = availability(
  "mission",
  "idle",
  "arming",
  "takeoff",
  "hover",
  "patrol",
  "returning",
  "landing",
  "completed",
  "aborted",
  "failed",
);

export const initialActionCatalog: ActionDefinition[] = [
  {
    action_name: "simulation.start",
    category: "simulation",
    description: "Start the simulation runtime session through the control plane.",
    input_schema: "SimulationStartRequest",
    result_schema: "ActionResult",
    target: "simulation",
    sync_mode: "async",
    availability: sessionStartable,
    owner_runtime: "shell_adapter",
  },
  {
    action_name: "simulation.stop",
    category: "simulation",
    description: "Stop the active simulation runtime session.",
    input_schema: "SimulationStopRequest",
    result_schema: "ActionResult",
    target: "simulation",
    sync_mode: "async",
    availability: sessionStoppable,
    owner_runtime: "shell_adapter",
  },
  {
    action_name: "simulation.restart",
    category: "simulation",
    description: "Restart the simulation runtime session through the control plane.",
    input_schema: "SimulationRestartRequest",
    result_schema: "ActionResult",
    target: "simulation",
    sync_mode: "async",
    availability: sessionAny,
    owner_runtime: "shell_adapter",
  },
  {
    action_name: "simulation.status.get",
    category: "simulation",
    description: "Read the current simulation session status.",
    input_schema: "EmptyObject",
    result_schema: "SimulationSession",
    target: "simulation",
    sync_mode: "sync",
    availability: sessionAny,
    owner_runtime: "control_plane",
    read_only: true,
  },
  {
    action_name: "capabilities.list",
    category: "discovery",
    description: "List capabilities exposed by the control plane for the current runtime.",
    input_schema: "EmptyObject",
    result_schema: "CapabilityList",
    target: "capability_registry",
    sync_mode: "sync",
    availability: [],
    owner_runtime: "control_plane",
    read_only: true,
  },
  {
    action_name: "scenario.list",
    category: "scenario",
    description: "List the scenarios exposed by the control plane.",
    input_schema: "EmptyObject",
    result_schema: "ScenarioList",
    target: "scenario_registry",
    sync_mode: "sync",
    availability: sessionAny,
    owner_runtime: "control_plane",
    read_only: true,
  },
  {
    action_name: "scenario.run",
    category: "scenario",
    description: "Run a scenario without leaking its executor type to the caller.",
    input_schema: "ScenarioRunRequest",
    result_schema: "ActionResult",
    target: "scenario",
    sync_mode: "async",
    availability: sessionActive,
    owner_runtime: "scenario_runtime",
  },
  {
    action_name: "scenario.cancel",
    category: "scenario",
    description: "Request cancellation of an active scenario run.",
    input_schema: "ScenarioCancelRequest",
    result_schema: "ActionResult",
    target: "scenario",
    sync_mode: "async",
    availability: runActive,
    owner_runtime: "scenario_runtime",
  },
  {
    action_name: "scenario.status.get",
    category: "scenario",
    description: "Read the current run status for a scenario.",
    input_schema: "ScenarioStatusQuery",
    result_schema: "ScenarioStatus",
    target: "scenario",
    sync_mode: "sync",
    availability: [],
    owner_runtime: "control_plane",
    read_only: true,
  },
  {
    action_name: "mission.start",
    category: "mission",
    description: "Request mission execution through the ROS 2 mission runtime.",
    input_schema: "MissionStartRequest",
    result_schema: "ActionResult",
    target: "mission",
    sync_mode: "async",
    availability: [...sessionActive, { scope: "mission", allowed_statuses: ["idle"] }],
    owner_runtime: "ros2_adapter",
  },
  {
    action_name: "mission.abort",
    category: "mission",
    description: "Abort the active mission.",
    input_schema: "MissionAbortRequest",
    result_schema: "ActionResult",
    target: "mission",
    sync_mode: "async",
    availability: missionActive,
    owner_runtime: "ros2_adapter",
  },
  {
    action_name: "mission.reset",
    category: "mission",
    description: "Reset mission state after a terminal phase.",
    input_schema: "MissionResetRequest",
    result_schema: "ActionResult",
    target: "mission",
    sync_mode: "async",
    availability: missionResettable,
    owner_runtime: "ros2_adapter",
  },
  {
    action_name: "mission.status.get",
    category: "mission",
    description: "Read the consolidated mission status.",
    input_schema: "EmptyObject",
    result_schema: "MissionDefinition",
    target: "mission",
    sync_mode: "sync",
    availability: missionAny,
    owner_runtime: "read_model_adapter",
    read_only: true,
  },
  {
    action_name: "vehicle.arm",
    category: "vehicle",
    description: "Arm the active vehicle.",
    input_schema: "EmptyObject",
    result_schema: "ActionResult",
    target: "vehicle",
    sync_mode: "async",
    availability: sessionActive,
    owner_runtime: "ros2_adapter",
  },
  {
    action_name: "vehicle.disarm",
    category: "vehicle",
    description: "Disarm the active vehicle.",
    input_schema: "EmptyObject",
    result_schema: "ActionResult",
    target: "vehicle",
    sync_mode: "async",
    availability: sessionActive,
    owner_runtime: "ros2_adapter",
  },
  {
    action_name: "vehicle.takeoff",
    category: "vehicle",
    description: "Trigger a direct vehicle takeoff action.",
    input_schema: "VehicleTakeoffRequest",
    result_schema: "ActionResult",
    target: "vehicle",
    sync_mode: "async",
    availability: sessionActive,
    owner_runtime: "ros2_adapter",
  },
  {
    action_name: "vehicle.land",
    category: "vehicle",
    description: "Request a landing action.",
    input_schema: "EmptyObject",
    result_schema: "ActionResult",
    target: "vehicle",
    sync_mode: "async",
    availability: sessionActive,
    owner_runtime: "ros2_adapter",
  },
  {
    action_name: "vehicle.return_to_home",
    category: "vehicle",
    description: "Request return-to-home for the current vehicle.",
    input_schema: "EmptyObject",
    result_schema: "ActionResult",
    target: "vehicle",
    sync_mode: "async",
    availability: sessionActive,
    owner_runtime: "ros2_adapter",
  },
  {
    action_name: "vehicle.goto",
    category: "vehicle",
    description: "Request a goto operation using product-level coordinates.",
    input_schema: "VehicleGotoRequest",
    result_schema: "ActionResult",
    target: "vehicle",
    sync_mode: "async",
    availability: sessionActive,
    owner_runtime: "ros2_adapter",
  },
  {
    action_name: "safety.inject_fault",
    category: "safety",
    description: "Inject a safety fault through the protected safety runtime.",
    input_schema: "SafetyFaultInjectionRequest",
    result_schema: "ActionResult",
    target: "safety",
    sync_mode: "async",
    availability: sessionActive,
    owner_runtime: "ros2_adapter",
  },
  {
    action_name: "safety.clear_fault",
    category: "safety",
    description: "Clear a previously injected safety fault.",
    input_schema: "SafetyFaultClearRequest",
    result_schema: "ActionResult",
    target: "safety",
    sync_mode: "async",
    availability: sessionActive,
    owner_runtime: "ros2_adapter",
  },
  {
    action_name: "safety.status.get",
    category: "safety",
    description: "Read the current safety status.",
    input_schema: "EmptyObject",
    result_schema: "SafetyStatus",
    target: "safety",
    sync_mode: "sync",
    availability: sessionAny,
    owner_runtime: "read_model_adapter",
    read_only: true,
  },
  {
    action_name: "perception.status.get",
    category: "perception",
    description: "Read the perception pipeline operational status.",
    input_schema: "EmptyObject",
    result_schema: "PerceptionStatus",
    target: "perception",
    sync_mode: "sync",
    availability: sessionActive,
    owner_runtime: "read_model_adapter",
    read_only: true,
  },
  {
    action_name: "perception.stream.status.get",
    category: "perception",
    description: "Read the camera or perception stream availability state.",
    input_schema: "EmptyObject",
    result_schema: "PerceptionStreamStatus",
    target: "perception_stream",
    sync_mode: "sync",
    availability: sessionActive,
    owner_runtime: "read_model_adapter",
    read_only: true,
  },
  {
    action_name: "telemetry.snapshot.get",
    category: "telemetry",
    description: "Read the consolidated telemetry snapshot.",
    input_schema: "EmptyObject",
    result_schema: "TelemetrySnapshot",
    target: "read_model",
    sync_mode: "sync",
    availability: sessionAny,
    owner_runtime: "read_model_adapter",
    read_only: true,
  },
  {
    action_name: "telemetry.metrics.get",
    category: "telemetry",
    description: "Read telemetry metrics for the active or requested run.",
    input_schema: "TelemetryMetricsQuery",
    result_schema: "TelemetryMetrics",
    target: "read_model",
    sync_mode: "sync",
    availability: sessionAny,
    owner_runtime: "read_model_adapter",
    read_only: true,
  },
  {
    action_name: "telemetry.events.get",
    category: "telemetry",
    description: "Read persisted telemetry events.",
    input_schema: "TelemetryEventsQuery",
    result_schema: "TelemetryEvents",
    target: "read_model",
    sync_mode: "sync",
    availability: sessionAny,
    owner_runtime: "read_model_adapter",
    read_only: true,
  },
  {
    action_name: "telemetry.runs.list",
    category: "telemetry",
    description: "List control-plane visible runs.",
    input_schema: "EmptyObject",
    result_schema: "RunList",
    target: "read_model",
    sync_mode: "sync",
    availability: sessionAny,
    owner_runtime: "read_model_adapter",
    read_only: true,
  },
  {
    action_name: "telemetry.replay.get",
    category: "telemetry",
    description: "Read replay data for a given run.",
    input_schema: "TelemetryReplayQuery",
    result_schema: "TelemetryReplay",
    target: "read_model",
    sync_mode: "sync",
    availability: sessionAny,
    owner_runtime: "read_model_adapter",
    read_only: true,
  },
];

export const initialCapabilityCatalog: CapabilityDefinition[] = [
  {
    capability_name: "simulation.lifecycle",
    version: "1.0.0",
    description: "Manage the simulation session lifecycle through the control plane.",
    action_names: ["simulation.start", "simulation.stop", "simulation.restart", "simulation.status.get"],
    required_runtime_components: ["simulation", "px4", "gazebo", "micro_xrce_dds_agent"],
    constraints: { visual_supported: true, headless_supported: true },
    owner_runtime: "shell_adapter",
    required_vehicle_type: "aerial_multirotor",
    required_environment: ["simulation"],
    safety_level: "guarded",
    status: "available",
  },
  {
    capability_name: "scenario.takeoff_land.run",
    version: "1.0.0",
    description: "Run the takeoff_land scenario against the active runtime.",
    action_names: ["scenario.run", "scenario.cancel", "scenario.status.get"],
    required_runtime_components: ["simulation", "px4", "gazebo", "mavsdk"],
    constraints: { scenario_name: "takeoff_land", visual_supported: true, headless_supported: true },
    owner_runtime: "mavsdk_adapter",
    required_vehicle_type: "aerial_multirotor",
    required_environment: ["simulation"],
    safety_level: "guarded",
    status: "available",
  },
  {
    capability_name: "scenario.patrol_basic.run",
    version: "1.0.0",
    description: "Run the patrol_basic mission-backed scenario through the control plane.",
    action_names: ["scenario.run", "scenario.cancel", "scenario.status.get"],
    required_runtime_components: ["simulation", "ros2", "mission_runtime", "px4"],
    constraints: { scenario_name: "patrol_basic", visual_supported: true, headless_supported: true },
    owner_runtime: "mission_runtime",
    required_vehicle_type: "aerial_multirotor",
    required_environment: ["simulation"],
    safety_level: "guarded",
    status: "available",
  },
  {
    capability_name: "mission.control",
    version: "1.0.0",
    description: "Operate mission lifecycle actions without direct topic publishing.",
    action_names: ["mission.start", "mission.abort", "mission.reset", "mission.status.get"],
    required_runtime_components: ["ros2", "mission_runtime"],
    constraints: { requires_active_session: true },
    owner_runtime: "mission_runtime",
    required_vehicle_type: "aerial_multirotor",
    required_environment: ["simulation"],
    safety_level: "guarded",
    status: "available",
  },
  {
    capability_name: "vehicle.basic_control",
    version: "1.0.0",
    description: "Operate core vehicle commands through the unified control surface.",
    action_names: ["vehicle.arm", "vehicle.disarm", "vehicle.takeoff", "vehicle.land", "vehicle.return_to_home", "vehicle.goto"],
    required_runtime_components: ["ros2", "px4"],
    constraints: { requires_connected_vehicle: true },
    owner_runtime: "vehicle_runtime",
    required_vehicle_type: "aerial_multirotor",
    required_environment: ["simulation"],
    safety_level: "critical",
    status: "available",
  },
  {
    capability_name: "safety.fault_injection",
    version: "1.0.0",
    description: "Inject or clear faults through the safety runtime without bypassing its policy logic.",
    action_names: ["safety.inject_fault", "safety.clear_fault", "safety.status.get"],
    required_runtime_components: ["ros2", "safety_runtime"],
    constraints: { operator_confirmation_required: true },
    owner_runtime: "safety_runtime",
    required_vehicle_type: "aerial_multirotor",
    required_environment: ["simulation"],
    safety_level: "critical",
    status: "available",
  },
  {
    capability_name: "telemetry.read_model",
    version: "1.0.0",
    description: "Read snapshot, metrics, events and run lists from the read model.",
    action_names: ["telemetry.snapshot.get", "telemetry.metrics.get", "telemetry.events.get", "telemetry.runs.list"],
    required_runtime_components: ["telemetry_api"],
    constraints: { read_only: true },
    owner_runtime: "read_model",
    required_vehicle_type: "aerial_multirotor",
    required_environment: ["simulation"],
    safety_level: "none",
    status: "available",
  },
  {
    capability_name: "replay.read",
    version: "1.0.0",
    description: "Access persisted replay artifacts by run id.",
    action_names: ["telemetry.replay.get"],
    required_runtime_components: ["telemetry_api"],
    constraints: { read_only: true, requires_run_id: true },
    owner_runtime: "read_model",
    required_vehicle_type: "aerial_multirotor",
    required_environment: ["simulation"],
    safety_level: "none",
    status: "available",
  },
  {
    capability_name: "perception.observe",
    version: "1.0.0",
    description: "Observe perception heartbeat, detections and stream status.",
    action_names: ["perception.status.get", "perception.stream.status.get", "telemetry.snapshot.get"],
    required_runtime_components: ["ros2", "perception_runtime", "telemetry_api"],
    constraints: { stream_may_depend_on_environment: true },
    owner_runtime: "perception_runtime",
    required_vehicle_type: "aerial_multirotor",
    required_payloads: ["camera"],
    required_environment: ["simulation"],
    safety_level: "advisory",
    status: "available",
  },
];
